package com.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yl.baiduren.entity.greenentity.AssetsnDetailesInformation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ASSETSN_DETAILES_INFORMATION".
*/
public class AssetsnDetailesInformationDao extends AbstractDao<AssetsnDetailesInformation, Long> {

    public static final String TABLENAME = "ASSETSN_DETAILES_INFORMATION";

    /**
     * Properties of entity AssetsnDetailesInformation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AId = new Property(0, Long.class, "aId", true, "_id");
        public final static Property Text = new Property(1, String.class, "text", false, "Text");
    }


    public AssetsnDetailesInformationDao(DaoConfig config) {
        super(config);
    }
    
    public AssetsnDetailesInformationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ASSETSN_DETAILES_INFORMATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: aId
                "\"Text\" TEXT);"); // 1: text
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ASSETSN_DETAILES_INFORMATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AssetsnDetailesInformation entity) {
        stmt.clearBindings();
 
        Long aId = entity.getAId();
        if (aId != null) {
            stmt.bindLong(1, aId);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(2, text);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AssetsnDetailesInformation entity) {
        stmt.clearBindings();
 
        Long aId = entity.getAId();
        if (aId != null) {
            stmt.bindLong(1, aId);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(2, text);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AssetsnDetailesInformation readEntity(Cursor cursor, int offset) {
        AssetsnDetailesInformation entity = new AssetsnDetailesInformation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // aId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // text
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AssetsnDetailesInformation entity, int offset) {
        entity.setAId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setText(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AssetsnDetailesInformation entity, long rowId) {
        entity.setAId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AssetsnDetailesInformation entity) {
        if(entity != null) {
            return entity.getAId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AssetsnDetailesInformation entity) {
        return entity.getAId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
