package com.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yl.baiduren.base.BaseRequest;
import com.yl.baiduren.entity.greenentity.AssetDO;
import com.yl.baiduren.entity.greenentity.AssetsnDetailesInformation;
import com.yl.baiduren.entity.greenentity.CategoryDo;
import com.yl.baiduren.entity.greenentity.DebtPerson;
import com.yl.baiduren.entity.greenentity.DemandDO;
import com.yl.baiduren.entity.greenentity.GoodLoanDO;
import com.yl.baiduren.entity.greenentity.Hall_Querry;
import com.yl.baiduren.entity.greenentity.LoginSuccess;
import com.yl.baiduren.entity.greenentity.MoneyLoanDO;
import com.yl.baiduren.entity.greenentity.MortgageDO;
import com.yl.baiduren.entity.greenentity.My_Delisting_Query;
import com.yl.baiduren.entity.greenentity.PayRecord;
import com.yl.baiduren.entity.greenentity.PropertyLoanDO;
import com.yl.baiduren.entity.greenentity.SponsorDO;
import com.yl.baiduren.entity.greenentity.Supply_Serch_Dao;
import com.yl.baiduren.entity.greenentity.Sussful_Exple_Query;
import com.yl.baiduren.entity.result.LoginPassword;
import com.yl.baiduren.entity.result.MyPager;

import com.greendao.BaseRequestDao;
import com.greendao.AssetDODao;
import com.greendao.AssetsnDetailesInformationDao;
import com.greendao.CategoryDoDao;
import com.greendao.DebtPersonDao;
import com.greendao.DemandDODao;
import com.greendao.GoodLoanDODao;
import com.greendao.Hall_QuerryDao;
import com.greendao.LoginSuccessDao;
import com.greendao.MoneyLoanDODao;
import com.greendao.MortgageDODao;
import com.greendao.My_Delisting_QueryDao;
import com.greendao.PayRecordDao;
import com.greendao.PropertyLoanDODao;
import com.greendao.SponsorDODao;
import com.greendao.Supply_Serch_DaoDao;
import com.greendao.Sussful_Exple_QueryDao;
import com.greendao.LoginPasswordDao;
import com.greendao.MyPagerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseRequestDaoConfig;
    private final DaoConfig assetDODaoConfig;
    private final DaoConfig assetsnDetailesInformationDaoConfig;
    private final DaoConfig categoryDoDaoConfig;
    private final DaoConfig debtPersonDaoConfig;
    private final DaoConfig demandDODaoConfig;
    private final DaoConfig goodLoanDODaoConfig;
    private final DaoConfig hall_QuerryDaoConfig;
    private final DaoConfig loginSuccessDaoConfig;
    private final DaoConfig moneyLoanDODaoConfig;
    private final DaoConfig mortgageDODaoConfig;
    private final DaoConfig my_Delisting_QueryDaoConfig;
    private final DaoConfig payRecordDaoConfig;
    private final DaoConfig propertyLoanDODaoConfig;
    private final DaoConfig sponsorDODaoConfig;
    private final DaoConfig supply_Serch_DaoDaoConfig;
    private final DaoConfig sussful_Exple_QueryDaoConfig;
    private final DaoConfig loginPasswordDaoConfig;
    private final DaoConfig myPagerDaoConfig;

    private final BaseRequestDao baseRequestDao;
    private final AssetDODao assetDODao;
    private final AssetsnDetailesInformationDao assetsnDetailesInformationDao;
    private final CategoryDoDao categoryDoDao;
    private final DebtPersonDao debtPersonDao;
    private final DemandDODao demandDODao;
    private final GoodLoanDODao goodLoanDODao;
    private final Hall_QuerryDao hall_QuerryDao;
    private final LoginSuccessDao loginSuccessDao;
    private final MoneyLoanDODao moneyLoanDODao;
    private final MortgageDODao mortgageDODao;
    private final My_Delisting_QueryDao my_Delisting_QueryDao;
    private final PayRecordDao payRecordDao;
    private final PropertyLoanDODao propertyLoanDODao;
    private final SponsorDODao sponsorDODao;
    private final Supply_Serch_DaoDao supply_Serch_DaoDao;
    private final Sussful_Exple_QueryDao sussful_Exple_QueryDao;
    private final LoginPasswordDao loginPasswordDao;
    private final MyPagerDao myPagerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseRequestDaoConfig = daoConfigMap.get(BaseRequestDao.class).clone();
        baseRequestDaoConfig.initIdentityScope(type);

        assetDODaoConfig = daoConfigMap.get(AssetDODao.class).clone();
        assetDODaoConfig.initIdentityScope(type);

        assetsnDetailesInformationDaoConfig = daoConfigMap.get(AssetsnDetailesInformationDao.class).clone();
        assetsnDetailesInformationDaoConfig.initIdentityScope(type);

        categoryDoDaoConfig = daoConfigMap.get(CategoryDoDao.class).clone();
        categoryDoDaoConfig.initIdentityScope(type);

        debtPersonDaoConfig = daoConfigMap.get(DebtPersonDao.class).clone();
        debtPersonDaoConfig.initIdentityScope(type);

        demandDODaoConfig = daoConfigMap.get(DemandDODao.class).clone();
        demandDODaoConfig.initIdentityScope(type);

        goodLoanDODaoConfig = daoConfigMap.get(GoodLoanDODao.class).clone();
        goodLoanDODaoConfig.initIdentityScope(type);

        hall_QuerryDaoConfig = daoConfigMap.get(Hall_QuerryDao.class).clone();
        hall_QuerryDaoConfig.initIdentityScope(type);

        loginSuccessDaoConfig = daoConfigMap.get(LoginSuccessDao.class).clone();
        loginSuccessDaoConfig.initIdentityScope(type);

        moneyLoanDODaoConfig = daoConfigMap.get(MoneyLoanDODao.class).clone();
        moneyLoanDODaoConfig.initIdentityScope(type);

        mortgageDODaoConfig = daoConfigMap.get(MortgageDODao.class).clone();
        mortgageDODaoConfig.initIdentityScope(type);

        my_Delisting_QueryDaoConfig = daoConfigMap.get(My_Delisting_QueryDao.class).clone();
        my_Delisting_QueryDaoConfig.initIdentityScope(type);

        payRecordDaoConfig = daoConfigMap.get(PayRecordDao.class).clone();
        payRecordDaoConfig.initIdentityScope(type);

        propertyLoanDODaoConfig = daoConfigMap.get(PropertyLoanDODao.class).clone();
        propertyLoanDODaoConfig.initIdentityScope(type);

        sponsorDODaoConfig = daoConfigMap.get(SponsorDODao.class).clone();
        sponsorDODaoConfig.initIdentityScope(type);

        supply_Serch_DaoDaoConfig = daoConfigMap.get(Supply_Serch_DaoDao.class).clone();
        supply_Serch_DaoDaoConfig.initIdentityScope(type);

        sussful_Exple_QueryDaoConfig = daoConfigMap.get(Sussful_Exple_QueryDao.class).clone();
        sussful_Exple_QueryDaoConfig.initIdentityScope(type);

        loginPasswordDaoConfig = daoConfigMap.get(LoginPasswordDao.class).clone();
        loginPasswordDaoConfig.initIdentityScope(type);

        myPagerDaoConfig = daoConfigMap.get(MyPagerDao.class).clone();
        myPagerDaoConfig.initIdentityScope(type);

        baseRequestDao = new BaseRequestDao(baseRequestDaoConfig, this);
        assetDODao = new AssetDODao(assetDODaoConfig, this);
        assetsnDetailesInformationDao = new AssetsnDetailesInformationDao(assetsnDetailesInformationDaoConfig, this);
        categoryDoDao = new CategoryDoDao(categoryDoDaoConfig, this);
        debtPersonDao = new DebtPersonDao(debtPersonDaoConfig, this);
        demandDODao = new DemandDODao(demandDODaoConfig, this);
        goodLoanDODao = new GoodLoanDODao(goodLoanDODaoConfig, this);
        hall_QuerryDao = new Hall_QuerryDao(hall_QuerryDaoConfig, this);
        loginSuccessDao = new LoginSuccessDao(loginSuccessDaoConfig, this);
        moneyLoanDODao = new MoneyLoanDODao(moneyLoanDODaoConfig, this);
        mortgageDODao = new MortgageDODao(mortgageDODaoConfig, this);
        my_Delisting_QueryDao = new My_Delisting_QueryDao(my_Delisting_QueryDaoConfig, this);
        payRecordDao = new PayRecordDao(payRecordDaoConfig, this);
        propertyLoanDODao = new PropertyLoanDODao(propertyLoanDODaoConfig, this);
        sponsorDODao = new SponsorDODao(sponsorDODaoConfig, this);
        supply_Serch_DaoDao = new Supply_Serch_DaoDao(supply_Serch_DaoDaoConfig, this);
        sussful_Exple_QueryDao = new Sussful_Exple_QueryDao(sussful_Exple_QueryDaoConfig, this);
        loginPasswordDao = new LoginPasswordDao(loginPasswordDaoConfig, this);
        myPagerDao = new MyPagerDao(myPagerDaoConfig, this);

        registerDao(BaseRequest.class, baseRequestDao);
        registerDao(AssetDO.class, assetDODao);
        registerDao(AssetsnDetailesInformation.class, assetsnDetailesInformationDao);
        registerDao(CategoryDo.class, categoryDoDao);
        registerDao(DebtPerson.class, debtPersonDao);
        registerDao(DemandDO.class, demandDODao);
        registerDao(GoodLoanDO.class, goodLoanDODao);
        registerDao(Hall_Querry.class, hall_QuerryDao);
        registerDao(LoginSuccess.class, loginSuccessDao);
        registerDao(MoneyLoanDO.class, moneyLoanDODao);
        registerDao(MortgageDO.class, mortgageDODao);
        registerDao(My_Delisting_Query.class, my_Delisting_QueryDao);
        registerDao(PayRecord.class, payRecordDao);
        registerDao(PropertyLoanDO.class, propertyLoanDODao);
        registerDao(SponsorDO.class, sponsorDODao);
        registerDao(Supply_Serch_Dao.class, supply_Serch_DaoDao);
        registerDao(Sussful_Exple_Query.class, sussful_Exple_QueryDao);
        registerDao(LoginPassword.class, loginPasswordDao);
        registerDao(MyPager.class, myPagerDao);
    }
    
    public void clear() {
        baseRequestDaoConfig.clearIdentityScope();
        assetDODaoConfig.clearIdentityScope();
        assetsnDetailesInformationDaoConfig.clearIdentityScope();
        categoryDoDaoConfig.clearIdentityScope();
        debtPersonDaoConfig.clearIdentityScope();
        demandDODaoConfig.clearIdentityScope();
        goodLoanDODaoConfig.clearIdentityScope();
        hall_QuerryDaoConfig.clearIdentityScope();
        loginSuccessDaoConfig.clearIdentityScope();
        moneyLoanDODaoConfig.clearIdentityScope();
        mortgageDODaoConfig.clearIdentityScope();
        my_Delisting_QueryDaoConfig.clearIdentityScope();
        payRecordDaoConfig.clearIdentityScope();
        propertyLoanDODaoConfig.clearIdentityScope();
        sponsorDODaoConfig.clearIdentityScope();
        supply_Serch_DaoDaoConfig.clearIdentityScope();
        sussful_Exple_QueryDaoConfig.clearIdentityScope();
        loginPasswordDaoConfig.clearIdentityScope();
        myPagerDaoConfig.clearIdentityScope();
    }

    public BaseRequestDao getBaseRequestDao() {
        return baseRequestDao;
    }

    public AssetDODao getAssetDODao() {
        return assetDODao;
    }

    public AssetsnDetailesInformationDao getAssetsnDetailesInformationDao() {
        return assetsnDetailesInformationDao;
    }

    public CategoryDoDao getCategoryDoDao() {
        return categoryDoDao;
    }

    public DebtPersonDao getDebtPersonDao() {
        return debtPersonDao;
    }

    public DemandDODao getDemandDODao() {
        return demandDODao;
    }

    public GoodLoanDODao getGoodLoanDODao() {
        return goodLoanDODao;
    }

    public Hall_QuerryDao getHall_QuerryDao() {
        return hall_QuerryDao;
    }

    public LoginSuccessDao getLoginSuccessDao() {
        return loginSuccessDao;
    }

    public MoneyLoanDODao getMoneyLoanDODao() {
        return moneyLoanDODao;
    }

    public MortgageDODao getMortgageDODao() {
        return mortgageDODao;
    }

    public My_Delisting_QueryDao getMy_Delisting_QueryDao() {
        return my_Delisting_QueryDao;
    }

    public PayRecordDao getPayRecordDao() {
        return payRecordDao;
    }

    public PropertyLoanDODao getPropertyLoanDODao() {
        return propertyLoanDODao;
    }

    public SponsorDODao getSponsorDODao() {
        return sponsorDODao;
    }

    public Supply_Serch_DaoDao getSupply_Serch_DaoDao() {
        return supply_Serch_DaoDao;
    }

    public Sussful_Exple_QueryDao getSussful_Exple_QueryDao() {
        return sussful_Exple_QueryDao;
    }

    public LoginPasswordDao getLoginPasswordDao() {
        return loginPasswordDao;
    }

    public MyPagerDao getMyPagerDao() {
        return myPagerDao;
    }

}
