package com.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yl.baiduren.entity.greenentity.Supply_Serch_Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SUPPLY__SERCH__DAO".
*/
public class Supply_Serch_DaoDao extends AbstractDao<Supply_Serch_Dao, Long> {

    public static final String TABLENAME = "SUPPLY__SERCH__DAO";

    /**
     * Properties of entity Supply_Serch_Dao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Supply_serch = new Property(1, String.class, "supply_serch", false, "supply_serch");
    }


    public Supply_Serch_DaoDao(DaoConfig config) {
        super(config);
    }
    
    public Supply_Serch_DaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SUPPLY__SERCH__DAO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"supply_serch\" TEXT);"); // 1: supply_serch
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SUPPLY__SERCH__DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Supply_Serch_Dao entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String supply_serch = entity.getSupply_serch();
        if (supply_serch != null) {
            stmt.bindString(2, supply_serch);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Supply_Serch_Dao entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String supply_serch = entity.getSupply_serch();
        if (supply_serch != null) {
            stmt.bindString(2, supply_serch);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Supply_Serch_Dao readEntity(Cursor cursor, int offset) {
        Supply_Serch_Dao entity = new Supply_Serch_Dao( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // supply_serch
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Supply_Serch_Dao entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSupply_serch(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Supply_Serch_Dao entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Supply_Serch_Dao entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Supply_Serch_Dao entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
